# Generated by Django 3.2.20 on 2023-09-15 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0006_alter_booking_booked_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date_booked_on']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booked_on',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_booked_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time_booked_on',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
