# Generated by Django 3.2.20 on 2023-09-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0008_auto_20230915_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='updated_on',
        ),
    ]
