# Generated by Django 3.2.20 on 2023-09-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0009_remove_booking_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'time']},
        ),
    ]
