# Generated by Django 3.2.20 on 2023-09-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0011_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date']},
        ),
    ]
