# Generated by Django 3.2.20 on 2023-09-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0012_alter_booking_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_on',
        ),
    ]
