# Generated by Django 3.2.20 on 2023-09-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0015_booking_booking_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_submitted',
        ),
    ]
